### ISSUE TITLE
Bump to 2.0?

### ISSUE THREAD

**Issue by toddanglin** [mavris/MMLanScanPod#1]
Eager to try the improvements in MMLanScan 2.0. Would it be possible to bump and publish the MMLanScan pod to 2.0?

**Comment by mavris** [comment]
hey, I started to add (a while ago) MMLanScan to pod but I forgot about it. Is this working for v1?

**Comment by toddanglin** [comment]
It looks like the pod was never published to the public directory, but testing from your repo, it seems to work! Would be great to see the Pod source include all the latest and greatest in 2.0, and perhaps see the "official" pod published to the public directory. :)

I'm ultimately consuming this pod in a NativeScript application, and my quick tests there suggest it's working there, too. Will try to wrap this native Pod in an NPM package to make even easier to consume in NativeScript apps. Just want to do it for the latest API.

**Comment by mavris** [comment]
I tried to convert it for CocoaPods but seriously I spent almost 3-4 hours on it without any luck. I am sorry but I can't spend more time at the moment. I will try again in the future. In the meantime if you have the knowledge to add it on CocoaPods please send me a pull request.

**Comment by toddanglin** [comment]
Thanks for trying! I don't have a lot of experience creating CocoaPods, but I will take a look. Maybe I can enlist the help from some NativeScript community experts...

**Comment by toddanglin** [comment]
Unless I'm missing something, I think the CocoaPod works when simply replacing the current 1.0 MMLanScan sources with the new 2.0 sources. I forked this repo to give it a try and it's working for me in my local testing...https://github.com/toddanglin/MMLanScanPod

**Comment by mavris** [comment]
Did you try the command: `pod spec lint MMLanScan.podspec` ? It cant be uploaded to CocoaPods public repo if it doesn't pass this check. That was my problem

**Comment by mavris** [comment]
Hey, MMLanScan is now available through CocoaPods

**Comment by toddanglin** [comment]
That's great! Thanks.

We've also successfully wrapped MMLanSan as a plugin that can be used in NativeScript apps:
https://www.npmjs.com/package/nativescript-lan-scan

We'll get that updated to use the official pod.
